### ISSUE TITLE
Need responsive styled paginator & Footer

### ISSUE THREAD

**Issue by sannoob** [Saebasol-hibiscus/hibiscus-frontend#13]
![image](https://user-images.githubusercontent.com/40298015/133250360-841122eb-b887-412e-bb9e-69259353bcd0.png)

**Comment by SaidBySolo** [comment]
paginator fixed in https://github.com/Saebasol-hibiscus/hibiscus-frontend/commit/3f0559e298c8a152914a364de72481574b15ccf0
